[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"

[[redirects]]
  from = "/api/groq/*"
  to = "https://api.groq.com/openai/v1/:splat"
  status = 200
  force = true

