[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"

[[redirects]]
  from = "/api/hf/*"
  to = "https://api-inference.huggingface.co/:splat"
  status = 200
  force = true

